version: '3.9'

services:

  postgres:
    container_name: postgres_container
    image: postgres:alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: S8Clients

  zookeeper:
    container_name: zookeeper_container
    image: zookeeper
    ports:
      - "2181:2181"

  kafka:
    container_name: kafka_container
    image: bitnami/kafka:latest
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ADVERTISED_HOST_NAME: kafka
      ALLOW_PLAINTEXT_LISTENER: "yes"
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_NUM_PARTITIONS: 12
    restart: unless-stopped

  ebanking-api:
    container_name: ebanking_api_container
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    image: ebanking-api
    environment:
       SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/S8Clients
       SPRING_DATASOURCE_USERNAME: postgres
       SPRING_DATASOURCE_PASSWORD: postgres
       SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
    - postgres
    - kafka
    - zookeeper
    restart: on-failure
