version: '3.9'

services:

  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: kafka
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_ZOOKEPER_CONNECT: zookeper:32181

  postgres:
    image: postgres:alpine
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ebanking_db

  ebanking-app:
    container_name: ebanking-app
    build:
      context: .
      dockerfile: Dockerfile
    image: ebanking-app
    restart: always
    environment:
      POSTGRES_DB: ebanking_db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRESQL_PORT: 5432
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - kafka
    links:
      - postgres
