version: 2.1
jobs:
  s8-building-testing:
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - checkout
      - run:
          name: Building
          command: mvn clean package -Dmaven.test.skip
      - run:
          name: Testing
          command: mvn test
workflows:
  version: 2
  build-deploy:
    jobs:
      - s8-building-testing
